const quotes = [
  { text: "Small habits create big and lasting change." },
  { text: "Focus on getting one percent better every day." },
  { text: "Systems shape your results more than goals do." },
  { text: "Habits are the compound interest of self-improvement." },
  { text: "Tiny changes bring remarkable results over time." },
  { text: "Consistency beats intensity when building habits." },
  { text: "Your habits shape your identity every day." },
  { text: "Success is built on small, repeated actions." },
  { text: "Design your surroundings to support good habits." },
  { text: "You don’t need to wait for motivation, just create a clear plan." },
  { text: "Focus on the daily actions, not only the final result." },
  { text: "You become what you do regularly." },
  { text: "Habits are easier when you enjoy them." },
  { text: "Success comes from small, smart choices daily." },
  { text: "Identity change starts with tiny actions." },
  { text: "Create habits that match the kind of person you want to become." },
  { text: "Remove anything that makes good habits difficult to start." },
  { text: "Keep repeating small actions until they become natural." },
  { text: "Improvement is slow at first, then unstoppable." },
  { text: "Show up every day, even if progress feels small." },
  { text: "Start small today; big results will follow with time." },
  { text: "Make habits so easy that skipping feels harder than doing." },
  { text: "Celebrate every small win to stay motivated." },
  { text: "Your future depends on the choices you repeat now." },
  { text: "Make good habits the default option, not the hard option." },
  { text: "Track your progress to see how far you’ve come." },
  { text: "Prepare your environment so the right choice is the easy one." },
  { text: "Every action you take is a vote for who you want to be." },
  { text: "Do not break the chain; keep your streak alive." },
  { text: "You don’t need to be perfect, just stay consistent." },
];

export default quotes;